//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthCareMvc5.LogInServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LogInServiceReference.ILogInService")]
    public interface ILogInService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogInService/ListOrganizationName", ReplyAction="http://tempuri.org/ILogInService/ListOrganizationNameResponse")]
        HealthCareObjects.UserRights.Login1[] ListOrganizationName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogInService/ListOrganizationName", ReplyAction="http://tempuri.org/ILogInService/ListOrganizationNameResponse")]
        System.Threading.Tasks.Task<HealthCareObjects.UserRights.Login1[]> ListOrganizationNameAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogInService/MyUserName", ReplyAction="http://tempuri.org/ILogInService/MyUserNameResponse")]
        HealthCareObjects.UserRights.Login1 MyUserName(string UserName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogInService/MyUserName", ReplyAction="http://tempuri.org/ILogInService/MyUserNameResponse")]
        System.Threading.Tasks.Task<HealthCareObjects.UserRights.Login1> MyUserNameAsync(string UserName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogInService/Orgname", ReplyAction="http://tempuri.org/ILogInService/OrgnameResponse")]
        string Orgname(string OrganizationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogInService/Orgname", ReplyAction="http://tempuri.org/ILogInService/OrgnameResponse")]
        System.Threading.Tasks.Task<string> OrgnameAsync(string OrganizationCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogInService/UserDetails", ReplyAction="http://tempuri.org/ILogInService/UserDetailsResponse")]
        HealthCareObjects.UserRights.Login1 UserDetails(string UserName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogInService/UserDetails", ReplyAction="http://tempuri.org/ILogInService/UserDetailsResponse")]
        System.Threading.Tasks.Task<HealthCareObjects.UserRights.Login1> UserDetailsAsync(string UserName, string Password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILogInServiceChannel : HealthCareMvc5.LogInServiceReference.ILogInService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LogInServiceClient : System.ServiceModel.ClientBase<HealthCareMvc5.LogInServiceReference.ILogInService>, HealthCareMvc5.LogInServiceReference.ILogInService {
        
        public LogInServiceClient() {
        }
        
        public LogInServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LogInServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogInServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogInServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HealthCareObjects.UserRights.Login1[] ListOrganizationName() {
            return base.Channel.ListOrganizationName();
        }
        
        public System.Threading.Tasks.Task<HealthCareObjects.UserRights.Login1[]> ListOrganizationNameAsync() {
            return base.Channel.ListOrganizationNameAsync();
        }
        
        public HealthCareObjects.UserRights.Login1 MyUserName(string UserName, string Password) {
            return base.Channel.MyUserName(UserName, Password);
        }
        
        public System.Threading.Tasks.Task<HealthCareObjects.UserRights.Login1> MyUserNameAsync(string UserName, string Password) {
            return base.Channel.MyUserNameAsync(UserName, Password);
        }
        
        public string Orgname(string OrganizationCode) {
            return base.Channel.Orgname(OrganizationCode);
        }
        
        public System.Threading.Tasks.Task<string> OrgnameAsync(string OrganizationCode) {
            return base.Channel.OrgnameAsync(OrganizationCode);
        }
        
        public HealthCareObjects.UserRights.Login1 UserDetails(string UserName, string Password) {
            return base.Channel.UserDetails(UserName, Password);
        }
        
        public System.Threading.Tasks.Task<HealthCareObjects.UserRights.Login1> UserDetailsAsync(string UserName, string Password) {
            return base.Channel.UserDetailsAsync(UserName, Password);
        }
    }
}
