//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthCareMvc5.IssueApprovalServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompliantApproval", Namespace="http://schemas.datacontract.org/2004/07/HealthCareObjects.Client")]
    [System.SerializableAttribute()]
    public partial class CompliantApproval : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActiveflagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ApprovalDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ApproveFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ClientIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ClientIssueNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompliantNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompliantRaisedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FeatureNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime IssueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IssueDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IssueDetailIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IssueidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IssuesubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ModifiedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ModifiedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModuleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NoOfIssueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OverAllPriorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SmcstatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalRecordsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activeflag {
            get {
                return this.ActiveflagField;
            }
            set {
                if ((this.ActiveflagField.Equals(value) != true)) {
                    this.ActiveflagField = value;
                    this.RaisePropertyChanged("Activeflag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ApprovalDate {
            get {
                return this.ApprovalDateField;
            }
            set {
                if ((this.ApprovalDateField.Equals(value) != true)) {
                    this.ApprovalDateField = value;
                    this.RaisePropertyChanged("ApprovalDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ApproveFlag {
            get {
                return this.ApproveFlagField;
            }
            set {
                if ((this.ApproveFlagField.Equals(value) != true)) {
                    this.ApproveFlagField = value;
                    this.RaisePropertyChanged("ApproveFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ClientID {
            get {
                return this.ClientIDField;
            }
            set {
                if ((this.ClientIDField.Equals(value) != true)) {
                    this.ClientIDField = value;
                    this.RaisePropertyChanged("ClientID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ClientIssueNo {
            get {
                return this.ClientIssueNoField;
            }
            set {
                if ((this.ClientIssueNoField.Equals(value) != true)) {
                    this.ClientIssueNoField = value;
                    this.RaisePropertyChanged("ClientIssueNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompliantNo {
            get {
                return this.CompliantNoField;
            }
            set {
                if ((object.ReferenceEquals(this.CompliantNoField, value) != true)) {
                    this.CompliantNoField = value;
                    this.RaisePropertyChanged("CompliantNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompliantRaisedBy {
            get {
                return this.CompliantRaisedByField;
            }
            set {
                if ((object.ReferenceEquals(this.CompliantRaisedByField, value) != true)) {
                    this.CompliantRaisedByField = value;
                    this.RaisePropertyChanged("CompliantRaisedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((this.CreatedByField.Equals(value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentName {
            get {
                return this.DepartmentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentNameField, value) != true)) {
                    this.DepartmentNameField = value;
                    this.RaisePropertyChanged("DepartmentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FeatureName {
            get {
                return this.FeatureNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FeatureNameField, value) != true)) {
                    this.FeatureNameField = value;
                    this.RaisePropertyChanged("FeatureName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormName {
            get {
                return this.FormNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FormNameField, value) != true)) {
                    this.FormNameField = value;
                    this.RaisePropertyChanged("FormName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime IssueDate {
            get {
                return this.IssueDateField;
            }
            set {
                if ((this.IssueDateField.Equals(value) != true)) {
                    this.IssueDateField = value;
                    this.RaisePropertyChanged("IssueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IssueDescription {
            get {
                return this.IssueDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.IssueDescriptionField, value) != true)) {
                    this.IssueDescriptionField = value;
                    this.RaisePropertyChanged("IssueDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IssueDetailID {
            get {
                return this.IssueDetailIDField;
            }
            set {
                if ((this.IssueDetailIDField.Equals(value) != true)) {
                    this.IssueDetailIDField = value;
                    this.RaisePropertyChanged("IssueDetailID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Issueid {
            get {
                return this.IssueidField;
            }
            set {
                if ((this.IssueidField.Equals(value) != true)) {
                    this.IssueidField = value;
                    this.RaisePropertyChanged("Issueid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Issuesubject {
            get {
                return this.IssuesubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.IssuesubjectField, value) != true)) {
                    this.IssuesubjectField = value;
                    this.RaisePropertyChanged("Issuesubject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ModifiedBy {
            get {
                return this.ModifiedByField;
            }
            set {
                if ((this.ModifiedByField.Equals(value) != true)) {
                    this.ModifiedByField = value;
                    this.RaisePropertyChanged("ModifiedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ModifiedDate {
            get {
                return this.ModifiedDateField;
            }
            set {
                if ((this.ModifiedDateField.Equals(value) != true)) {
                    this.ModifiedDateField = value;
                    this.RaisePropertyChanged("ModifiedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModuleName {
            get {
                return this.ModuleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ModuleNameField, value) != true)) {
                    this.ModuleNameField = value;
                    this.RaisePropertyChanged("ModuleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NoOfIssue {
            get {
                return this.NoOfIssueField;
            }
            set {
                if ((this.NoOfIssueField.Equals(value) != true)) {
                    this.NoOfIssueField = value;
                    this.RaisePropertyChanged("NoOfIssue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OverAllPriority {
            get {
                return this.OverAllPriorityField;
            }
            set {
                if ((object.ReferenceEquals(this.OverAllPriorityField, value) != true)) {
                    this.OverAllPriorityField = value;
                    this.RaisePropertyChanged("OverAllPriority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Priority {
            get {
                return this.PriorityField;
            }
            set {
                if ((object.ReferenceEquals(this.PriorityField, value) != true)) {
                    this.PriorityField = value;
                    this.RaisePropertyChanged("Priority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SNO {
            get {
                return this.SNOField;
            }
            set {
                if ((this.SNOField.Equals(value) != true)) {
                    this.SNOField = value;
                    this.RaisePropertyChanged("SNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Smcstatus {
            get {
                return this.SmcstatusField;
            }
            set {
                if ((this.SmcstatusField.Equals(value) != true)) {
                    this.SmcstatusField = value;
                    this.RaisePropertyChanged("Smcstatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalRecords {
            get {
                return this.TotalRecordsField;
            }
            set {
                if ((this.TotalRecordsField.Equals(value) != true)) {
                    this.TotalRecordsField = value;
                    this.RaisePropertyChanged("TotalRecords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IssueApproval", Namespace="http://schemas.datacontract.org/2004/07/HealthCareObjects.Client")]
    [System.SerializableAttribute()]
    public partial class IssueApproval : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AaprovalflagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ActiveflageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ApprovalDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AssignIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssignedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssignedNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AssignedToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AssigneeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CIssueIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CilentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ClosedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompltIssueNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DailyUpdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long DepartmentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long DeveloperIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeveloperNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FeatureNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FileUploadflagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsCompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsIssueNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IssueClientIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IssueDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IssueDetailIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IssueFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IssueFromIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IssueIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IssueSubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IssuesimpleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModulenameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoOfDaysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OurDescribtionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long PriorityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriorityNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SeverityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeverityNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShortNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TotalComplientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TotalRecordsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserFullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Aaprovalflag {
            get {
                return this.AaprovalflagField;
            }
            set {
                if ((this.AaprovalflagField.Equals(value) != true)) {
                    this.AaprovalflagField = value;
                    this.RaisePropertyChanged("Aaprovalflag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Activeflage {
            get {
                return this.ActiveflageField;
            }
            set {
                if ((this.ActiveflageField.Equals(value) != true)) {
                    this.ActiveflageField = value;
                    this.RaisePropertyChanged("Activeflage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ApprovalDate {
            get {
                return this.ApprovalDateField;
            }
            set {
                if ((this.ApprovalDateField.Equals(value) != true)) {
                    this.ApprovalDateField = value;
                    this.RaisePropertyChanged("ApprovalDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AssignID {
            get {
                return this.AssignIDField;
            }
            set {
                if ((this.AssignIDField.Equals(value) != true)) {
                    this.AssignIDField = value;
                    this.RaisePropertyChanged("AssignID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssignedBy {
            get {
                return this.AssignedByField;
            }
            set {
                if ((object.ReferenceEquals(this.AssignedByField, value) != true)) {
                    this.AssignedByField = value;
                    this.RaisePropertyChanged("AssignedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AssignedName {
            get {
                return this.AssignedNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AssignedNameField, value) != true)) {
                    this.AssignedNameField = value;
                    this.RaisePropertyChanged("AssignedName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AssignedTo {
            get {
                return this.AssignedToField;
            }
            set {
                if ((this.AssignedToField.Equals(value) != true)) {
                    this.AssignedToField = value;
                    this.RaisePropertyChanged("AssignedTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Assignee {
            get {
                return this.AssigneeField;
            }
            set {
                if ((object.ReferenceEquals(this.AssigneeField, value) != true)) {
                    this.AssigneeField = value;
                    this.RaisePropertyChanged("Assignee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CIssueID {
            get {
                return this.CIssueIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CIssueIDField, value) != true)) {
                    this.CIssueIDField = value;
                    this.RaisePropertyChanged("CIssueID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CilentID {
            get {
                return this.CilentIDField;
            }
            set {
                if ((this.CilentIDField.Equals(value) != true)) {
                    this.CilentIDField = value;
                    this.RaisePropertyChanged("CilentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ClosedDate {
            get {
                return this.ClosedDateField;
            }
            set {
                if ((this.ClosedDateField.Equals(value) != true)) {
                    this.ClosedDateField = value;
                    this.RaisePropertyChanged("ClosedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompltIssueNo {
            get {
                return this.CompltIssueNoField;
            }
            set {
                if ((object.ReferenceEquals(this.CompltIssueNoField, value) != true)) {
                    this.CompltIssueNoField = value;
                    this.RaisePropertyChanged("CompltIssueNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((this.CreatedByField.Equals(value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DailyUpdate {
            get {
                return this.DailyUpdateField;
            }
            set {
                if ((object.ReferenceEquals(this.DailyUpdateField, value) != true)) {
                    this.DailyUpdateField = value;
                    this.RaisePropertyChanged("DailyUpdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long DepartmentID {
            get {
                return this.DepartmentIDField;
            }
            set {
                if ((this.DepartmentIDField.Equals(value) != true)) {
                    this.DepartmentIDField = value;
                    this.RaisePropertyChanged("DepartmentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentName {
            get {
                return this.DepartmentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentNameField, value) != true)) {
                    this.DepartmentNameField = value;
                    this.RaisePropertyChanged("DepartmentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long DeveloperID {
            get {
                return this.DeveloperIDField;
            }
            set {
                if ((this.DeveloperIDField.Equals(value) != true)) {
                    this.DeveloperIDField = value;
                    this.RaisePropertyChanged("DeveloperID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeveloperName {
            get {
                return this.DeveloperNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DeveloperNameField, value) != true)) {
                    this.DeveloperNameField = value;
                    this.RaisePropertyChanged("DeveloperName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DueDate {
            get {
                return this.DueDateField;
            }
            set {
                if ((this.DueDateField.Equals(value) != true)) {
                    this.DueDateField = value;
                    this.RaisePropertyChanged("DueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FeatureName {
            get {
                return this.FeatureNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FeatureNameField, value) != true)) {
                    this.FeatureNameField = value;
                    this.RaisePropertyChanged("FeatureName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FileUploadflag {
            get {
                return this.FileUploadflagField;
            }
            set {
                if ((this.FileUploadflagField.Equals(value) != true)) {
                    this.FileUploadflagField = value;
                    this.RaisePropertyChanged("FileUploadflag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Formname {
            get {
                return this.FormnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FormnameField, value) != true)) {
                    this.FormnameField = value;
                    this.RaisePropertyChanged("Formname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromDate {
            get {
                return this.FromDateField;
            }
            set {
                if ((object.ReferenceEquals(this.FromDateField, value) != true)) {
                    this.FromDateField = value;
                    this.RaisePropertyChanged("FromDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsCompany {
            get {
                return this.IsCompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.IsCompanyField, value) != true)) {
                    this.IsCompanyField = value;
                    this.RaisePropertyChanged("IsCompany");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsIssueNO {
            get {
                return this.IsIssueNOField;
            }
            set {
                if ((object.ReferenceEquals(this.IsIssueNOField, value) != true)) {
                    this.IsIssueNOField = value;
                    this.RaisePropertyChanged("IsIssueNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IssueClientID {
            get {
                return this.IssueClientIDField;
            }
            set {
                if ((this.IssueClientIDField.Equals(value) != true)) {
                    this.IssueClientIDField = value;
                    this.RaisePropertyChanged("IssueClientID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IssueDescription {
            get {
                return this.IssueDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.IssueDescriptionField, value) != true)) {
                    this.IssueDescriptionField = value;
                    this.RaisePropertyChanged("IssueDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IssueDetailID {
            get {
                return this.IssueDetailIDField;
            }
            set {
                if ((this.IssueDetailIDField.Equals(value) != true)) {
                    this.IssueDetailIDField = value;
                    this.RaisePropertyChanged("IssueDetailID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IssueFrom {
            get {
                return this.IssueFromField;
            }
            set {
                if ((object.ReferenceEquals(this.IssueFromField, value) != true)) {
                    this.IssueFromField = value;
                    this.RaisePropertyChanged("IssueFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IssueFromId {
            get {
                return this.IssueFromIdField;
            }
            set {
                if ((this.IssueFromIdField.Equals(value) != true)) {
                    this.IssueFromIdField = value;
                    this.RaisePropertyChanged("IssueFromId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IssueID {
            get {
                return this.IssueIDField;
            }
            set {
                if ((this.IssueIDField.Equals(value) != true)) {
                    this.IssueIDField = value;
                    this.RaisePropertyChanged("IssueID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IssueSubject {
            get {
                return this.IssueSubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.IssueSubjectField, value) != true)) {
                    this.IssueSubjectField = value;
                    this.RaisePropertyChanged("IssueSubject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Issuesimple {
            get {
                return this.IssuesimpleField;
            }
            set {
                if ((object.ReferenceEquals(this.IssuesimpleField, value) != true)) {
                    this.IssuesimpleField = value;
                    this.RaisePropertyChanged("Issuesimple");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Modulename {
            get {
                return this.ModulenameField;
            }
            set {
                if ((object.ReferenceEquals(this.ModulenameField, value) != true)) {
                    this.ModulenameField = value;
                    this.RaisePropertyChanged("Modulename");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NoOfDays {
            get {
                return this.NoOfDaysField;
            }
            set {
                if ((object.ReferenceEquals(this.NoOfDaysField, value) != true)) {
                    this.NoOfDaysField = value;
                    this.RaisePropertyChanged("NoOfDays");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OurDescribtion {
            get {
                return this.OurDescribtionField;
            }
            set {
                if ((object.ReferenceEquals(this.OurDescribtionField, value) != true)) {
                    this.OurDescribtionField = value;
                    this.RaisePropertyChanged("OurDescribtion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Priority {
            get {
                return this.PriorityField;
            }
            set {
                if ((object.ReferenceEquals(this.PriorityField, value) != true)) {
                    this.PriorityField = value;
                    this.RaisePropertyChanged("Priority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long PriorityId {
            get {
                return this.PriorityIdField;
            }
            set {
                if ((this.PriorityIdField.Equals(value) != true)) {
                    this.PriorityIdField = value;
                    this.RaisePropertyChanged("PriorityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PriorityName {
            get {
                return this.PriorityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PriorityNameField, value) != true)) {
                    this.PriorityNameField = value;
                    this.RaisePropertyChanged("PriorityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SNO {
            get {
                return this.SNOField;
            }
            set {
                if ((this.SNOField.Equals(value) != true)) {
                    this.SNOField = value;
                    this.RaisePropertyChanged("SNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SeverityId {
            get {
                return this.SeverityIdField;
            }
            set {
                if ((this.SeverityIdField.Equals(value) != true)) {
                    this.SeverityIdField = value;
                    this.RaisePropertyChanged("SeverityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SeverityName {
            get {
                return this.SeverityNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SeverityNameField, value) != true)) {
                    this.SeverityNameField = value;
                    this.RaisePropertyChanged("SeverityName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShortName {
            get {
                return this.ShortNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ShortNameField, value) != true)) {
                    this.ShortNameField = value;
                    this.RaisePropertyChanged("ShortName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToDate {
            get {
                return this.ToDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ToDateField, value) != true)) {
                    this.ToDateField = value;
                    this.RaisePropertyChanged("ToDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TotalComplient {
            get {
                return this.TotalComplientField;
            }
            set {
                if ((object.ReferenceEquals(this.TotalComplientField, value) != true)) {
                    this.TotalComplientField = value;
                    this.RaisePropertyChanged("TotalComplient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TotalRecords {
            get {
                return this.TotalRecordsField;
            }
            set {
                if ((this.TotalRecordsField.Equals(value) != true)) {
                    this.TotalRecordsField = value;
                    this.RaisePropertyChanged("TotalRecords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserFullName {
            get {
                return this.UserFullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserFullNameField, value) != true)) {
                    this.UserFullNameField = value;
                    this.RaisePropertyChanged("UserFullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClientIssueRaise", Namespace="http://schemas.datacontract.org/2004/07/HealthCareObjects.Client")]
    [System.SerializableAttribute()]
    public partial class ClientIssueRaise : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ActiveflageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AssignedIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CIssueIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ClientAddressIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ClientIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ClientNameIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompltIssueNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ContactNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CreatedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatedDate1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreatedDate2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateofIntializationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long FeatureIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FeatureNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long FileUploadFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long FilecountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long FormIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FormNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IsSaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> IssueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime IssueDate1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IssueDate2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IssueIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IssueSubjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IssueTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IssueTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IssueTypeNameIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IssuedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ModuleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModuleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SelfAssignField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerialNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShortNmaeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TotalRecordsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fileNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Activeflage {
            get {
                return this.ActiveflageField;
            }
            set {
                if ((this.ActiveflageField.Equals(value) != true)) {
                    this.ActiveflageField = value;
                    this.RaisePropertyChanged("Activeflage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AssignedID {
            get {
                return this.AssignedIDField;
            }
            set {
                if ((this.AssignedIDField.Equals(value) != true)) {
                    this.AssignedIDField = value;
                    this.RaisePropertyChanged("AssignedID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CIssueID {
            get {
                return this.CIssueIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CIssueIDField, value) != true)) {
                    this.CIssueIDField = value;
                    this.RaisePropertyChanged("CIssueID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ClientAddressID {
            get {
                return this.ClientAddressIDField;
            }
            set {
                if ((this.ClientAddressIDField.Equals(value) != true)) {
                    this.ClientAddressIDField = value;
                    this.RaisePropertyChanged("ClientAddressID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ClientID {
            get {
                return this.ClientIDField;
            }
            set {
                if ((this.ClientIDField.Equals(value) != true)) {
                    this.ClientIDField = value;
                    this.RaisePropertyChanged("ClientID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientName {
            get {
                return this.ClientNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientNameField, value) != true)) {
                    this.ClientNameField = value;
                    this.RaisePropertyChanged("ClientName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ClientNameID {
            get {
                return this.ClientNameIDField;
            }
            set {
                if ((this.ClientNameIDField.Equals(value) != true)) {
                    this.ClientNameIDField = value;
                    this.RaisePropertyChanged("ClientNameID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompltIssueNo {
            get {
                return this.CompltIssueNoField;
            }
            set {
                if ((object.ReferenceEquals(this.CompltIssueNoField, value) != true)) {
                    this.CompltIssueNoField = value;
                    this.RaisePropertyChanged("CompltIssueNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ContactNo {
            get {
                return this.ContactNoField;
            }
            set {
                if ((this.ContactNoField.Equals(value) != true)) {
                    this.ContactNoField = value;
                    this.RaisePropertyChanged("ContactNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CreatedBy {
            get {
                return this.CreatedByField;
            }
            set {
                if ((this.CreatedByField.Equals(value) != true)) {
                    this.CreatedByField = value;
                    this.RaisePropertyChanged("CreatedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedDate1 {
            get {
                return this.CreatedDate1Field;
            }
            set {
                if ((object.ReferenceEquals(this.CreatedDate1Field, value) != true)) {
                    this.CreatedDate1Field = value;
                    this.RaisePropertyChanged("CreatedDate1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedDate2 {
            get {
                return this.CreatedDate2Field;
            }
            set {
                if ((this.CreatedDate2Field.Equals(value) != true)) {
                    this.CreatedDate2Field = value;
                    this.RaisePropertyChanged("CreatedDate2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateofIntialization {
            get {
                return this.DateofIntializationField;
            }
            set {
                if ((this.DateofIntializationField.Equals(value) != true)) {
                    this.DateofIntializationField = value;
                    this.RaisePropertyChanged("DateofIntialization");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentID {
            get {
                return this.DepartmentIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentIDField, value) != true)) {
                    this.DepartmentIDField = value;
                    this.RaisePropertyChanged("DepartmentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepartmentName {
            get {
                return this.DepartmentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentNameField, value) != true)) {
                    this.DepartmentNameField = value;
                    this.RaisePropertyChanged("DepartmentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailId {
            get {
                return this.EmailIdField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailIdField, value) != true)) {
                    this.EmailIdField = value;
                    this.RaisePropertyChanged("EmailId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long FeatureID {
            get {
                return this.FeatureIDField;
            }
            set {
                if ((this.FeatureIDField.Equals(value) != true)) {
                    this.FeatureIDField = value;
                    this.RaisePropertyChanged("FeatureID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FeatureName {
            get {
                return this.FeatureNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FeatureNameField, value) != true)) {
                    this.FeatureNameField = value;
                    this.RaisePropertyChanged("FeatureName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] File {
            get {
                return this.FileField;
            }
            set {
                if ((object.ReferenceEquals(this.FileField, value) != true)) {
                    this.FileField = value;
                    this.RaisePropertyChanged("File");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long FileUploadFlag {
            get {
                return this.FileUploadFlagField;
            }
            set {
                if ((this.FileUploadFlagField.Equals(value) != true)) {
                    this.FileUploadFlagField = value;
                    this.RaisePropertyChanged("FileUploadFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Filecount {
            get {
                return this.FilecountField;
            }
            set {
                if ((this.FilecountField.Equals(value) != true)) {
                    this.FilecountField = value;
                    this.RaisePropertyChanged("Filecount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long FormID {
            get {
                return this.FormIDField;
            }
            set {
                if ((this.FormIDField.Equals(value) != true)) {
                    this.FormIDField = value;
                    this.RaisePropertyChanged("FormID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FormName {
            get {
                return this.FormNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FormNameField, value) != true)) {
                    this.FormNameField = value;
                    this.RaisePropertyChanged("FormName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IsSave {
            get {
                return this.IsSaveField;
            }
            set {
                if ((this.IsSaveField.Equals(value) != true)) {
                    this.IsSaveField = value;
                    this.RaisePropertyChanged("IsSave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> IssueDate {
            get {
                return this.IssueDateField;
            }
            set {
                if ((this.IssueDateField.Equals(value) != true)) {
                    this.IssueDateField = value;
                    this.RaisePropertyChanged("IssueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime IssueDate1 {
            get {
                return this.IssueDate1Field;
            }
            set {
                if ((this.IssueDate1Field.Equals(value) != true)) {
                    this.IssueDate1Field = value;
                    this.RaisePropertyChanged("IssueDate1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IssueDate2 {
            get {
                return this.IssueDate2Field;
            }
            set {
                if ((object.ReferenceEquals(this.IssueDate2Field, value) != true)) {
                    this.IssueDate2Field = value;
                    this.RaisePropertyChanged("IssueDate2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IssueID {
            get {
                return this.IssueIDField;
            }
            set {
                if ((this.IssueIDField.Equals(value) != true)) {
                    this.IssueIDField = value;
                    this.RaisePropertyChanged("IssueID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IssueSubject {
            get {
                return this.IssueSubjectField;
            }
            set {
                if ((object.ReferenceEquals(this.IssueSubjectField, value) != true)) {
                    this.IssueSubjectField = value;
                    this.RaisePropertyChanged("IssueSubject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IssueType {
            get {
                return this.IssueTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.IssueTypeField, value) != true)) {
                    this.IssueTypeField = value;
                    this.RaisePropertyChanged("IssueType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IssueTypeID {
            get {
                return this.IssueTypeIDField;
            }
            set {
                if ((this.IssueTypeIDField.Equals(value) != true)) {
                    this.IssueTypeIDField = value;
                    this.RaisePropertyChanged("IssueTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IssueTypeNameId {
            get {
                return this.IssueTypeNameIdField;
            }
            set {
                if ((this.IssueTypeNameIdField.Equals(value) != true)) {
                    this.IssueTypeNameIdField = value;
                    this.RaisePropertyChanged("IssueTypeNameId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IssuedBy {
            get {
                return this.IssuedByField;
            }
            set {
                if ((this.IssuedByField.Equals(value) != true)) {
                    this.IssuedByField = value;
                    this.RaisePropertyChanged("IssuedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ModuleID {
            get {
                return this.ModuleIDField;
            }
            set {
                if ((this.ModuleIDField.Equals(value) != true)) {
                    this.ModuleIDField = value;
                    this.RaisePropertyChanged("ModuleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModuleName {
            get {
                return this.ModuleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ModuleNameField, value) != true)) {
                    this.ModuleNameField = value;
                    this.RaisePropertyChanged("ModuleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductNo {
            get {
                return this.ProductNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNoField, value) != true)) {
                    this.ProductNoField = value;
                    this.RaisePropertyChanged("ProductNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SNo {
            get {
                return this.SNoField;
            }
            set {
                if ((this.SNoField.Equals(value) != true)) {
                    this.SNoField = value;
                    this.RaisePropertyChanged("SNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SelfAssign {
            get {
                return this.SelfAssignField;
            }
            set {
                if ((this.SelfAssignField.Equals(value) != true)) {
                    this.SelfAssignField = value;
                    this.RaisePropertyChanged("SelfAssign");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SerialNo {
            get {
                return this.SerialNoField;
            }
            set {
                if ((object.ReferenceEquals(this.SerialNoField, value) != true)) {
                    this.SerialNoField = value;
                    this.RaisePropertyChanged("SerialNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShortNmae {
            get {
                return this.ShortNmaeField;
            }
            set {
                if ((object.ReferenceEquals(this.ShortNmaeField, value) != true)) {
                    this.ShortNmaeField = value;
                    this.RaisePropertyChanged("ShortNmae");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TotalRecords {
            get {
                return this.TotalRecordsField;
            }
            set {
                if ((this.TotalRecordsField.Equals(value) != true)) {
                    this.TotalRecordsField = value;
                    this.RaisePropertyChanged("TotalRecords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.fileNameField, value) != true)) {
                    this.fileNameField = value;
                    this.RaisePropertyChanged("fileName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IssueApprovalServiceRef.IIssueApprovalService")]
    public interface IIssueApprovalService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIssueApprovalService/Updateissueapproval", ReplyAction="http://tempuri.org/IIssueApprovalService/UpdateissueapprovalResponse")]
        bool Updateissueapproval(HealthCareMvc5.IssueApprovalServiceRef.CompliantApproval objCompliantNO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIssueApprovalService/Updateissueapproval", ReplyAction="http://tempuri.org/IIssueApprovalService/UpdateissueapprovalResponse")]
        System.Threading.Tasks.Task<bool> UpdateissueapprovalAsync(HealthCareMvc5.IssueApprovalServiceRef.CompliantApproval objCompliantNO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIssueApprovalService/ListUpdate", ReplyAction="http://tempuri.org/IIssueApprovalService/ListUpdateResponse")]
        bool ListUpdate(System.Collections.Generic.List<HealthCareMvc5.IssueApprovalServiceRef.CompliantApproval> objCompliantApproval);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIssueApprovalService/ListUpdate", ReplyAction="http://tempuri.org/IIssueApprovalService/ListUpdateResponse")]
        System.Threading.Tasks.Task<bool> ListUpdateAsync(System.Collections.Generic.List<HealthCareMvc5.IssueApprovalServiceRef.CompliantApproval> objCompliantApproval);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIssueApprovalService/ListMainPagebyUserID", ReplyAction="http://tempuri.org/IIssueApprovalService/ListMainPagebyUserIDResponse")]
        System.Collections.Generic.List<HealthCareMvc5.IssueApprovalServiceRef.IssueApproval> ListMainPagebyUserID(int PageNO, int RowperPage, long UserID, int ClientID, string SearchText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIssueApprovalService/ListMainPagebyUserID", ReplyAction="http://tempuri.org/IIssueApprovalService/ListMainPagebyUserIDResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<HealthCareMvc5.IssueApprovalServiceRef.IssueApproval>> ListMainPagebyUserIDAsync(int PageNO, int RowperPage, long UserID, int ClientID, string SearchText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIssueApprovalService/clientList", ReplyAction="http://tempuri.org/IIssueApprovalService/clientListResponse")]
        System.Collections.Generic.List<HealthCareMvc5.IssueApprovalServiceRef.ClientIssueRaise> clientList(long UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIssueApprovalService/clientList", ReplyAction="http://tempuri.org/IIssueApprovalService/clientListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<HealthCareMvc5.IssueApprovalServiceRef.ClientIssueRaise>> clientListAsync(long UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIssueApprovalService/ListGrid", ReplyAction="http://tempuri.org/IIssueApprovalService/ListGridResponse")]
        System.Collections.Generic.List<HealthCareMvc5.IssueApprovalServiceRef.CompliantApproval> ListGrid(long objissueDtlID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIssueApprovalService/ListGrid", ReplyAction="http://tempuri.org/IIssueApprovalService/ListGridResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<HealthCareMvc5.IssueApprovalServiceRef.CompliantApproval>> ListGridAsync(long objissueDtlID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIssueApprovalServiceChannel : HealthCareMvc5.IssueApprovalServiceRef.IIssueApprovalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IssueApprovalServiceClient : System.ServiceModel.ClientBase<HealthCareMvc5.IssueApprovalServiceRef.IIssueApprovalService>, HealthCareMvc5.IssueApprovalServiceRef.IIssueApprovalService {
        
        public IssueApprovalServiceClient() {
        }
        
        public IssueApprovalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IssueApprovalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IssueApprovalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IssueApprovalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Updateissueapproval(HealthCareMvc5.IssueApprovalServiceRef.CompliantApproval objCompliantNO) {
            return base.Channel.Updateissueapproval(objCompliantNO);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateissueapprovalAsync(HealthCareMvc5.IssueApprovalServiceRef.CompliantApproval objCompliantNO) {
            return base.Channel.UpdateissueapprovalAsync(objCompliantNO);
        }
        
        public bool ListUpdate(System.Collections.Generic.List<HealthCareMvc5.IssueApprovalServiceRef.CompliantApproval> objCompliantApproval) {
            return base.Channel.ListUpdate(objCompliantApproval);
        }
        
        public System.Threading.Tasks.Task<bool> ListUpdateAsync(System.Collections.Generic.List<HealthCareMvc5.IssueApprovalServiceRef.CompliantApproval> objCompliantApproval) {
            return base.Channel.ListUpdateAsync(objCompliantApproval);
        }
        
        public System.Collections.Generic.List<HealthCareMvc5.IssueApprovalServiceRef.IssueApproval> ListMainPagebyUserID(int PageNO, int RowperPage, long UserID, int ClientID, string SearchText) {
            return base.Channel.ListMainPagebyUserID(PageNO, RowperPage, UserID, ClientID, SearchText);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<HealthCareMvc5.IssueApprovalServiceRef.IssueApproval>> ListMainPagebyUserIDAsync(int PageNO, int RowperPage, long UserID, int ClientID, string SearchText) {
            return base.Channel.ListMainPagebyUserIDAsync(PageNO, RowperPage, UserID, ClientID, SearchText);
        }
        
        public System.Collections.Generic.List<HealthCareMvc5.IssueApprovalServiceRef.ClientIssueRaise> clientList(long UserID) {
            return base.Channel.clientList(UserID);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<HealthCareMvc5.IssueApprovalServiceRef.ClientIssueRaise>> clientListAsync(long UserID) {
            return base.Channel.clientListAsync(UserID);
        }
        
        public System.Collections.Generic.List<HealthCareMvc5.IssueApprovalServiceRef.CompliantApproval> ListGrid(long objissueDtlID) {
            return base.Channel.ListGrid(objissueDtlID);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<HealthCareMvc5.IssueApprovalServiceRef.CompliantApproval>> ListGridAsync(long objissueDtlID) {
            return base.Channel.ListGridAsync(objissueDtlID);
        }
    }
}
